from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from PySide6.QtGui import QPixmap

from .xsdk_ctypes import CameraPrecheckReport


@dataclass(slots=True)
class CameraDescriptor:
    model: str
    serial: str
    connection: str = "usb"


class CameraSdkAdapter(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_connected(self) -> bool: ...
    def connect_camera(self) -> CameraDescriptor: ...
    def disconnect_camera(self) -> None: ...
    def begin_live_view(self) -> None: ...
    def end_live_view(self) -> None: ...
    def get_live_view_frame(self) -> QPixmap: ...
    def enqueue_capture(self, output_dir: Path) -> None: ...
    def pop_capture_result(self) -> tuple[Path | None, str | None]: ...
    def run_precheck_safe(self) -> CameraPrecheckReport: ...
    def format_precheck_summary(self, report: CameraPrecheckReport) -> str: ...
