from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from PySide6.QtGui import QPixmap

from .xsdk_ctypes import CameraPrecheckReport


@dataclass(slots=True)
class CameraDescriptor:
    model: str
    serial: str
    connection: str = "usb"


class CameraSdkAdapter(Protocol):
    def start(self): ...
    def stop(self): ...
    def is_connected(self): ...
    def connect_camera(self): ...
    def disconnect_camera(self): ...
    def begin_live_view(self): ...
    def end_live_view(self): ...
    def get_live_view_frame(self): ...
    def enqueue_capture(self, output_dir): ...
    def pop_capture_result(self): ...
    def run_precheck_safe(self): ...
    def format_precheck_summary(self, report): ...
    def get_exposure_options(self): ...
    def get_exposure_state(self): ...
    def set_exposure(self, *, iso=None, shutter=None, aperture=None): ...
