from dataclasses import dataclass


class AdapterStopping(BaseException):
    pass


@dataclass(slots=True)
class CameraDescriptor:
    model: str
    serial: str
    connection: str = "usb"


class CameraSdkAdapter:
    def start(self): ...
    def stop(self): ...
    def is_connected(self): ...
    def connect_camera(self): ...
    def disconnect_camera(self): ...
    def begin_live_view(self): ...
    def end_live_view(self): ...
    def get_live_view_frame(self): ...
    def capture_photo(self, output_dir): ...
    def get_exposure_options(self): ...
    def get_exposure_state(self): ...
    def set_exposure(self, *, iso=None, shutter=None, aperture=None): ...
